spring:
  application:
    name: workflow-engine

  profiles:
    group:
      dev-jpa:
        - dev
        - jpa

      dev-pg:
        - dev
        - pg

      dev-memory:
        - dev
        - memory